[package]
name = "cat-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
mime = "0.3"
env_logger = "0.11.3"
log = "0.4"